<?php  

//QUANDO E NECESSARIO FAZER O GET DE ALGUM ARQUIVO QUE NAO SEJA EM FORMATO DE TEXTO/CSV, COMO FOTO E BINARIO, FAZ NECESSARIO O USO DO ? E O BETA64 PARA TRANSFORMAR ESSE BINARIO EM TEXTO PARA SER INTERPRETADO PELO NAVEGADOR/API/INTERFACE/ANEXOS.......

$filename = "farmers-e-hunter.jpg";

//FILE_GET_CONTENTES E POSSIVEL OS VALORES DE UM ARQUIVO, MESMO NAO SENDO TEXTO. RETORNA UMA STRING QUE SERA USADA COMO PARAMETRO PARA O BASE64_ENCODE ONDE TRANSFORMA A CADA 6 BYTES E M CARACTER TABELA ASCII
$base64 = base64_encode(file_get_contents($filename));


//OBJETO NATIVO DO PHP QUE POSSUI O METODO QUE E POSSIVEL OBTER O TIPO DE EXTERNSAO DO ARQUIVO, ASSIM UM CODIGO MAIS DINAMICO
$fileinfo = new finfo(FILEINFO_MIME_TYPE); 
$mimetype = $fileinfo->file($filename);

$base64encode = "data:".$mimetype.";base64,".$base64; 
?>
<!-- RENDERIZADO O BASE64 COM O HTML -->
<a href="<?$base64encode?>" target="_blank">LINK</a>

<img src="<?=$base64encode?>">