<?php  
//cURL 

$cep = "18071020";
$url = "viacep.com.br/ws/".$cep."/json/";

//COMO NA MANIPULACAO DE ARQUIVOS CRIA-SE UMA VARIAVEL PARA CONTROLAR QUAL BIBLIOTECA SERA USADA POSTERIORMENTE, AFINAL PODEMOS USAR VARIOS APIs
$ch = curl_init($url);

//CURLOPT_RETURNTRANSFER CONSTANTE DA LIB CURL, SIGNIFICA QUE EU ESPERO UM RETORNO DA REQUISICAO, TAMBEM EXISTE UMA MAO DE VOLTA SENDO 1 = TRUE
curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);

//CURLOPT_SSL_VERIFYPEER, COMO A API DO CORREIO JA POSSUI HTTPS O PARAMETRO E FALSO
curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, 0);

//COMO E UM GET APENAS ESSES DOIS PARAMETROS FORAM SUFICIENTES E BASTA EXECUTAR
$response = curl_exec($ch);

//ASSIM COMO NA MANIPULACAO DE ARQUIVOS SEMPRE QUE ABRE PRECISA FECHAR PARA NAO GASTAR RECURSOS DO SERVIDOR
curl_close($ch);


//MESMO NA URI DA API TER O END POINT /JSON O RETORNO E UM STRING E PARA MANIPULAR E NECESSARIOS TRANSFORMAR EM ARRAY, 2º PARAMETRO TRUE PARA NAO TRANSFORMAR EM UM OBJETO COMO PADRAO
$date = json_decode($response, true);

print_r($date);
echo "<br>";
echo $date['logradouro'];
?>